Add files via upload
instructlab/taxonomy pull request #1013
Opened 2024-05-09 15:53 UTC by b4d

https://github.com/instructlab/taxonomy/issues/839

2024-05-09 20:29 UTC, bjhargrave requested changes
The folder name has a misspelling that should be corrected.

`knowledge/science/astronomy_tech/radioisotope_thermo_generator/`

2024-05-13 16:27 UTC, jjasghar commented
Please fix the linting issue(s).

2024-05-14 13:54 UTC, jjasghar requested changes
Please resolve this issue.

2024-05-14 13:54 UTC, jjasghar commented on knowledge/science/astronomy_tech/radioisotope_thermo_generator/qna.yaml
> +created_by: Deni B
Please put your GitHub Username here

2024-05-14 13:54 UTC, jjasghar commented
Please delete the `.gitignore` and fix the DCO issue too.

2024-05-28 19:16 UTC, jjasghar commented
Please rebase off of main, and only commit your `attribution.txt` and `qna.yaml`.

2024-05-28 19:16 UTC, jjasghar requested changes
Please look above about the rebase.

2024-05-30 20:49 UTC, jjasghar commented
Closing due to combined PR here:  #1142

2024-05-30 20:49 UTC, closed without merging