Astronomy
instructlab/taxonomy pull request #1043
Opened 2024-05-09 17:58 UTC by jmtejal

2024-05-09 20:03 UTC, bjhargrave requested changes

2024-05-09 20:03 UTC, bjhargrave commented on knowledge/science/astronomy_tech/radioisotope_termo_generator/attribution.txt
> +created_by:
Please use a valid attribution file. This is just a copy of the qna.yaml.

2024-05-09 20:03 UTC, bjhargrave commented on knowledge/science/astronomy_tech/radioisotope_termo_generator/qna.yaml
> +task_description: ' '
Please provide a valid task description.

2024-05-09 20:03 UTC, bjhargrave commented on knowledge/science/astronomy_tech/radioisotope_termo_generator/qna.yaml
> +created_by:
This value must be your github id.

2024-05-09 20:04 UTC, bjhargrave commented
Also, the folder name has a misspelling that should be corrected.

`knowledge/science/astronomy_tech/radioisotope_thermo_generator`

2024-05-30 20:49 UTC, jjasghar commented
Closing due to combined PR here:  #1142

2024-05-30 20:49 UTC, closed without merging