Adds tabby cat knowledge to InstructLab
instructlab/taxonomy pull request #1060
Opened 2024-05-10 17:24 UTC by jregehr

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Adds Tabby Cat knowlege**

Signed-off-by: Regehr, Jonathan <10343188+jregehr@users.noreply.github.com>

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-10 18:14 UTC, jjasghar commented
@instructlab-bot precheck

2024-05-10 20:57 UTC, jjasghar commented
the `precheck` seems like the model already knows what a tabby cat is, @mingxzhao or @bjhargrave can you confirm what I'm seeing also?

2024-05-11 00:30 UTC, jregehr commented
JJ, I felt like my first PR was really messed up so I closed the PR,
deleted my fork, made a new fork, re-added the files, and made a new PR.

Sorry for the confusion.

- Jonathan
[sent from my mobile]


On Fri, May 10, 2024 at 3:57 PM JJ Asghar ***@***.***> wrote:

> the precheck seems like the model already knows what a tabby cat is,
> @mingxzhao <https://github.com/mingxzhao> or @bjhargrave
> <https://github.com/bjhargrave> can you confirm what I'm seeing also?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/instructlab/taxonomy/pull/1060#issuecomment-2105262188>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACO5GFGB5XXL2ICTWFHYFW3ZBUYEXAVCNFSM6AAAAABHQ7LWEGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBVGI3DEMJYHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-13 23:21 UTC, jjasghar requested changes
Please fix the created_by then we can run the linter.

2024-05-13 23:21 UTC, jjasghar commented on knowledge/animals/tabby_cat/qna.yaml
> +created_by: Jonathan Regehr
Please put your GitHub Username here.

2024-05-14 04:11 UTC, jregehr commented
Fixed!
- Jonathan


On Mon, May 13, 2024 at 6:21 PM JJ Asghar ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please fix the created_by then we can run the linter.
> ------------------------------
>
> In knowledge/animals/tabby_cat/qna.yaml
> <https://github.com/instructlab/taxonomy/pull/1060#discussion_r1599201362>
> :
>
> > @@ -0,0 +1,49 @@
> +created_by: Jonathan Regehr
>
> Please put your GitHub Username here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/instructlab/taxonomy/pull/1060#pullrequestreview-2053966091>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACO5GFC6QAE7IKKE6ID2VL3ZCFDJDAVCNFSM6AAAAABHQ7LWEGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJTHE3DMMBZGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-14 13:56 UTC, jjasghar commented
Please fix the DCO issue.

2024-05-16 16:17 UTC, jregehr commented
@jjasghar We talked about this PR at DevOpsDays KC :)

2024-05-17 21:24 UTC, jjasghar commented
Here's another linter broken @bjhargrave, it's not pulling the newest script for some reason. I'm not sure what's going on here.

2024-05-20 15:37 UTC, bjhargrave commented
> Here's another linter broken @bjhargrave, it's not pulling the newest script for some reason. I'm not sure what's going on here.

It needed a rebase to get the #1090 fix.

2024-05-20 22:36 UTC, jjasghar commented
@instructlab-bot precheck

2024-05-20 22:45 UTC, jjasghar commented
@nerdalert or @vishnoianil can you take a look at this one, the Precheck bot is :sadpanda:

2024-05-21 05:12 UTC, nerdalert commented
@instructlab-bot precheck

2024-05-21 05:17 UTC, nerdalert commented
@jjasghar Its a known bug, will bump it up. We have seen a couple of times that git manages to get into a weird state. Tossing the fork on the worker resolves it. Thanks for the heads up!

2024-05-23 23:17 UTC, ljmwaugh commented
I've merged your qna.yaml with another tabby_cat qna.yaml and the new PR is here
https://github.com/instructlab/taxonomy/pull/1118

2024-05-29 18:55 UTC, jjasghar commented
Closing per https://github.com/instructlab/taxonomy/pull/1118.

2024-05-29 18:55 UTC, closed without merging