Jasminum sambac knowledge
instructlab/taxonomy pull request #1067
Opened 2024-05-11 02:10 UTC by szemmour-rh

[#835](https://github.com/instructlab/taxonomy/issues/835)

2024-05-13 23:20 UTC, jjasghar requested changes
Please resolve these issues then we can run the linter.

2024-05-13 23:20 UTC, jjasghar commented on knowledge/science/botany/jasminum/qna.yaml
> +created_by: Samy Zemmouri
Please put your GitHub Username here.

2024-05-13 23:20 UTC, jjasghar commented on knowledge/science/botany/jasminum/qna.yaml
> +- answer: The English common name of "Arabian jasmine", Jasminum sambac is due to it being widely cultivated in Southwest of Saudi Arabia, Yemen and Oman|
Thank you for your submission; taking a look at your `qna.yaml`, we noticed that you have some issues with the multiline `yaml` syntax.

Can you take a look at: https://yaml-multiline.info/ and fix up the file? Thanks!

2024-05-13 23:29 UTC, jjasghar commented
@instructlab-bot precheck

2024-05-13 23:30 UTC, szemmour-rh commented
requested modification done

2024-05-29 22:54 UTC, jjasghar commented
Closed due to the combined PR here: https://github.com/instructlab/taxonomy/pull/1140

2024-05-29 22:54 UTC, closed without merging