[Knowledge] Add taxonomy for instruct-lab
instructlab/taxonomy pull request #1086
Opened 2024-05-15 18:38 UTC by harshit-sh

**Describe the contribution to the taxonomy**
- Train the model with instruct-lab related 'knowledge'.

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-16 15:35 UTC, bjhargrave requested changes
Please fix lint issues.

2024-05-16 15:42 UTC, jjasghar requested changes
Please fix the created_by, then we can run the linter.

2024-05-16 15:42 UTC, jjasghar commented on knowledge/technical_manual/instructlab/qna.yaml
> +created_by: Harshit
please put your GitHub Username here.

2024-05-28 20:38 UTC, bjhargrave commented
@mergifyio rebase

2024-05-28 20:40 UTC, bjhargrave commented
Please add

```yaml
version: 2
```

to the start of the qna.yaml file. This is now a requirement of the schema validation process during linting.

2024-06-04 07:02 UTC, harshit-sh commented on knowledge/technical_manual/instructlab/qna.yaml
> +created_by: Harshit
Updated the line.

2024-07-22 01:56 UTC, closed without merging