Skill: Simplify the complex legal language. Signed-off-by: Nishith Sh…
instructlab/taxonomy pull request #1109
Opened 2024-05-21 19:34 UTC by nishithsharma9

Nishith Sharma <ns5014@nyu.edu>

**Describe the contribution to the taxonomy**

- Simplify the complex legal language of the GDPR into plain English for easy comprehension.
- Extract and translate specific legal provisions on demand, provide example to easily understand, presenting them in a structured format for clarity.

**Input given at the prompt**
```
Discuss the GDPR's data minimization principle in the context of data breaches and the importance of implementing appropriate data protection measures.
```

**Response from the original model**
```
 ### GDPR's Data Minimization Principle:**Definition:**The General Data Protection Regulation (GDPR) is a European Union (EU) regulation that sets guidelines for the collection and processing of personal data of individuals within the EU. The data minimization principle is one of the key principles of the GDPR, which states that personal data should be adequate, relevant, and limited to what is necessary for the purposes for which it is processed.### Key Concepts and Components:1. **Adequacy:**   - Personal data should be collected to an extent that is relevant and not excessive for the purpose it is intended for.2. **Relevance:**   - The data collected should be relevant to the specific purpose of the processing activity.3. **Limitation:**   - Personal data should be limited to what is necessary for the purpose it is intended for.### Data Breaches and Data Minimization:A data breach occurs when sensitive, protected, or confidential data is copied, transmitted, viewed, stolen, or used by an individual without authorization. Implementing the data minimization principle can help reduce the
```

**Response from the fine-tuned model**
```
 The GDPR's data minimization principle requires organizations to collect and process only the personal data that is necessary for the specific purpose of the processing. This principle is crucial in the context of data breaches, as it helps to reduce the risk of unauthorized access, misuse, or loss of personal data. By implementing appropriate data protection measures in line with the data minimization principle, organizations can:- Reduce the amount of personal data stored, thereby minimizing the potential impact of a data breach;- Ensure that only authorized personnel have access to personal data, reducing the risk of insider threats;- Implement robust access controls, encryption, and other security measures to protect the personal data that is stored;- Regularly review and update data protection measures, ensuring that they remain effective in light of changes in the organization's operations, the threat landscape, or other factors.By adhering to the data minimization principle, organizations can not only reduce the risk of data breaches but also demonstrate their commitment to data protection and privacy, which can help to build trust with customers, employees, and other stakeholders. This, in turn, can help to protect the organization's reputation and prevent potential legal or financial consequences
```

**Contribution checklist**

- [x] The contribution was tested with `ilab generate`
- [x] No errors or warnings were produced by `ilab generate`
- [x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x] The `qna.yaml` file contains at least 5 `seed_examples`
- [x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x] Content does not include PII or otherwise sensitive or confidential information
- [x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-21 21:58 UTC, jjasghar requested changes

2024-05-21 21:58 UTC, jjasghar commented on compositional_skills/legal/article_comprehension/qna.yaml
> +created_by: Nishith Sharma
Please add your GitHub Username here.

2024-05-21 21:58 UTC, jjasghar commented on compositional_skills/legal/article_comprehension/qna.yaml
These answers feel ike they should be in the markdown referenced in a skill. This also seems opinionated and we can't reference it at a `sha` of that document.
I don't this this is a skill, more so a knowledge submission so we can verify the documentation and track back this "simplified language"

2024-05-21 21:58 UTC, jjasghar commented on compositional_skills/legal/article_comprehension/attribution.txt
Please take a look at the required fields in for the `attribution.txt` and fill it out with the needed data.

2024-05-22 14:22 UTC, nishithsharma9 commented on compositional_skills/legal/article_comprehension/qna.yaml
Hi @jjasghar,
Sharing brief of the task:
1. Skill-Based Task: The process involves explainability and summarization skills, transforming complex legal jargon into plain English for better comprehension.
2. Objective Simplification: Our approach objectively breaks down legal text without subjective interpretation, ensuring clarity and accessibility.
3. Traceability: There is no need for traceability as we are just simplifying the given text as input and using the same to make it easy to comprehend without extracting any other knowledge source.

2024-05-22 20:13 UTC, nishithsharma9 commented
Tagging here for reference: @adampingel

2024-07-21 01:57 UTC, closed without merging