prepare tabby_cat for PR
instructlab/taxonomy pull request #1118
Opened 2024-05-23 19:42 UTC by ljmwaugh

add tabby_cat knowledge by combining the tabby_cat files from Summit

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [X ] The contribution was tested with `ilab generate`
- [X ] No errors or warnings were produced by `ilab generate`
- [X ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [X ] The `qna.yaml` file contains at least 5 `seed_examples`
- [X ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [X ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [X ] Content does not include PII or otherwise sensitive or confidential information
- [X ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-23 22:35 UTC, jjasghar commented
@instructlab-bot precheck

2024-05-31 14:01 UTC, bjhargrave requested changes

2024-06-10 18:32 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> + repo: https://github.com/ljmwaugh/instructlab_knowledge.git
changed to use juliadenham

2024-06-10 18:32 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> +   question: What is an orange tabby?
removed the second question

2024-06-10 18:32 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> +   question: what are the patterns that tabby's have
made suggested change

2024-06-10 18:33 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> +   question: what is the origin of the name "tabby"
made suggested change

2024-06-10 18:33 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> +      distinctive M-shaped marking on their forehead, stripes by their
made suggested change

2024-06-10 18:33 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> +   question: how can you tell a cat is a tabby cat
made suggested change

2024-06-10 18:33 UTC, ljmwaugh commented on knowledge/animals/tabby_cat/qna.yaml
> +   question: what kind of cat are tabby
made suggested change

2024-06-10 19:00 UTC, bjhargrave commented
@instructlab-bot precheck

2024-06-11 15:06 UTC, bjhargrave requested changes

2024-06-11 15:07 UTC, bjhargrave commented
> Results can be found [here](https://instruct-lab-bot.s3.us-east-2.amazonaws.com/precheck-pr-1118-a1df9f9bf16f8c0ef62a19f58106d7e47923b3f4-job-396/index.html).

A number of questions had decent answers. Some did not. So once we update the commit for the knowledge document, we will do a generate check.

2024-06-11 21:03 UTC, bjhargrave commented
@instructlab-bot generate

2024-06-11 21:04 UTC, bjhargrave approved these changes

2024-06-14 18:54 UTC, bjhargrave requested changes
This is the tabby cat PR. Federation square knowledge needs to be in its own PR. 

I think your issue is that you are not using a separate git branch for each PR. Generally you should never work on your main branch and submit PRs from your main branch.

2024-06-14 21:33 UTC, ljmwaugh commented
@bjhargrave I've tried to clean it up.  Please let me know if I succeeded or if I need to do something additional.  I reverted the commit that added the federation_square.

2024-06-14 21:42 UTC, bjhargrave commented
@Mergifyio squash

2024-06-14 21:44 UTC, bjhargrave commented
I squashed the commits (which force pushed your main branch).

2024-06-26 18:17 UTC, closed without merging

2024-06-26 18:17 UTC, ljmwaugh commented
replaced by #1212