workflow: Add workflow to update CoC report on PR close event
instructlab/taxonomy pull request #1122
Opened 2024-05-24 18:53 UTC by nitin-ramchandani

Added a new workflow to automate the process of updating a Pull Request (PR) record when a PR is closed. The workflow sends an HTTP request to the Code of Conduct (CoC) Handler, ensuring that the PR status is accurately reflected in our records.

2024-05-28 16:35 UTC, bjhargrave requested changes

2024-05-28 16:35 UTC, bjhargrave commented on .github/workflows/update-CoC-report.yml
> +run-name: 'PR Closed: ${{ github.event.pull_request.number}} ${{ github.event.pull_request.title }}'
```suggestion
run-name: "${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number}})"

```

2024-05-28 16:35 UTC, bjhargrave commented on .github/workflows/update-CoC-report.yml
> +    types: [ closed ]
```suggestion
    types:
      - closed
```

2024-05-29 16:24 UTC, nitin-ramchandani commented on .github/workflows/update-CoC-report.yml
> +    runs-on: ubuntu-latest
Correct, updated

2024-05-29 17:06 UTC, bjhargrave commented
@mergifyio rebase

2024-05-29 17:11 UTC, bjhargrave approved these changes

2024-05-29 17:12 UTC, merged