Patch 1
instructlab/taxonomy pull request #1127
Opened 2024-05-25 09:03 UTC by JanaGK2

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**
- training the model on handling objections using the method of Acknowledgement and open clarifying question

 user prompt: We do not currently have budget allocated to purchase a new IT solution.
Proposed IT solution will save logistics cost.

expected output: Justifying budget for IT is challenging. How much extra logistics costs you incur due to poor IT performance?

-----model output BEFORE training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
LoRA init skipped
Total parameters 1242.375M
Trainable parameters 0.000M
Loading datasets
LoRA loading skipped
Generating
==========
I understand that you're looking for a way to save logistics costs without allocating a budget for a new IT solution. In this case, I suggest exploring existing solutions that can be implemented at no cost, such as optimizing your current IT infrastructure. This could involve improving processes, implementing automation, or making better use of the tools you already have. Here are some specific suggestions:

1. **Process Improvement:** Review your existing logistics workflows and identify
==========

-----model output AFTER training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
Generating
==========
How will we see the savings?
==========
[2]
 user prompt: We already have a provider of fraud detection and we are happy.
Proposed solution increases fraud detection by 20%.

expected output: Great you are satisfied. If fraud detection efficiency increased by 20%, how much would you save?

-----model output BEFORE training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
LoRA init skipped
Total parameters 1242.375M
Trainable parameters 0.000M
Loading datasets
LoRA loading skipped
Generating
==========
Why would you replace our current provider?
==========

-----model output AFTER training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
Generating
==========
Our provider already detects fraud effectively. This new solution will increase detection further.
==========
[3]
 user prompt: Your solution is too complex for our current needs.
Proposed solution supports fast business growth.

expected output: It is essential to have the right tools. How will your current solution scale with business growth?

-----model output BEFORE training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
LoRA init skipped
Total parameters 1242.375M
Trainable parameters 0.000M
Loading datasets
LoRA loading skipped
Generating
==========
Thank you for your feedback. We understand the needs of your business and will strive to provide an alternative solution that meets your current requirements while being cost-effective.
==========

-----model output AFTER training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
Generating
==========
Can we simplify or streamline the implementation process to meet our current needs?
==========
[4]
 user prompt: We are overloaded and I cannot let my experts work on training.
Proposed solutions shortens the onboarding of new experts.

expected output: I understand concerns about workload of your SMEs. How would it help to get additional experts faster?

-----model output BEFORE training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
LoRA init skipped
Total parameters 1242.375M
Trainable parameters 0.000M
Loading datasets
LoRA loading skipped
Generating
==========
I get it. Shortening the onboarding process can save a lot of time and resources for your experts. Would you like to share some tips for improving the onboarding experience for new experts?
==========

-----model output AFTER training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
Generating
==========
What are the benefits of training for your experts?
==========
[5]
 user prompt: We have a solid business and heavy investment would reduce our value to our investors.
Proposed solution will future-proof customer's business.

expected output: Maximization of shareholder value is crucial. How would stock price change if you lose market leadership.

-----model output BEFORE training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
LoRA init skipped
Total parameters 1242.375M
Trainable parameters 0.000M
Loading datasets
LoRA loading skipped
Generating
==========
If you are interested in future-proofing your business, I would like to introduce you to integrated marketing automation, which will improve your customer experience and drive business results. This solution involves integrating various marketing tools to create a cohesive, data-driven marketing strategy that adapts to your customers' needs and preferences. By doing so, you can maximize your marketing ROI and provide a seamless customer journey.
==========

-----model output AFTER training----:

Loading pretrained model
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
Generating
==========
What does our solution do that will future-proof our customers' business?

**Contribution checklist**

- [ x] The contribution was tested with `ilab generate`
- [x ] No errors or warnings were produced by `ilab generate`
- [ x] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [x ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ x] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ x] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [x ] Content does not include PII or otherwise sensitive or confidential information
- [ x] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-25 14:09 UTC, jjasghar requested changes

2024-05-25 14:09 UTC, jjasghar commented on compositional_skills/writing/grounded/objection_handling/generated_merlinite-7b-lab-Q4_K_M_2024-05-24T22_41_15.json
Please remove this file from the PR.

2024-05-25 14:15 UTC, JanaGK2 reviewed
I have removed the json file as requested.

2024-05-25 14:15 UTC, JanaGK2 commented on compositional_skills/writing/grounded/objection_handling/generated_merlinite-7b-lab-Q4_K_M_2024-05-24T22_41_15.json
Will try to do!

2024-05-28 18:56 UTC, jjasghar approved these changes

2024-05-28 18:57 UTC, jjasghar commented
@instructlab-bot precheck

2024-05-28 19:01 UTC, jjasghar requested changes

2024-05-28 19:01 UTC, jjasghar commented on compositional_skills/writing/grounded/objection_handling/qna.yaml
These are statements, and not questions. The precheck came back with unhelpful statements, so I don't think this will work.

2024-05-28 19:01 UTC, jjasghar commented on compositional_skills/writing/grounded/objection_handling/attribution.txt
> +Link to work: https://docs.google.com/document/d/1XZjABlQsE1L7-AYdXOb_lwBNEg9lKOrVuRb_HjsGY-o/edit?usp=sharing
Also, I'm not 100% sure if the legal team can allow content from random doc.google.com domains.

2024-05-28 21:56 UTC, jjasghar commented
Hi, so we discussed this in our triage meeting today. We have decided to close this due to the mismanagement of what you are trying to do and what the model can do.
One of the challenges is that the model can't answer a question by asking the following question.  Thank you for your submission but this is incapable right now.

2024-05-28 21:56 UTC, closed without merging