Jason Kelce (combined)
instructlab/taxonomy pull request #1144
Opened 2024-05-30 21:29 UTC by jjasghar

This is the combined  Jason Kelce PRs from Red Hat Summit 2024.

This superseeds #1028 #946

2024-05-31 13:39 UTC, bjhargrave requested changes

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +task_description: ' '
This need a proper task description.

For example:

```suggestion
task_description: 'To teach a language model about the person Jason Kelce'
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +- answer: Clevelan Heights, Ohio
```suggestion
- answer: Cleveland Heights, Ohio
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: What other teams did Jason Kelce play for besides Philadelphia?
```suggestion
  question: What other NFL teams did Jason Kelce play for besides Philadelphia?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: What round was Jason Kelce drafted?
```suggestion
  question: What round of the NFL draft was Jason Kelce drafted?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: What's Jason Kelce's brother's name?
```suggestion
  question: What is the name of Jason Kelce's brother?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: how many games Jason Kelce played so far?
```suggestion
  question: How many NFL games Jason Kelce played?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: What position does Jason Kelce play?
```suggestion
  question: What NFL position does Jason Kelce play?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: How many games Jason Kelce played in the year 2015?
```suggestion
  question: How many NFL games did Jason Kelce play in the year 2015?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +  question: when did Jason Kelce was born?
```suggestion
  question: When was Jason Kelce born?
```

2024-05-31 13:39 UTC, bjhargrave commented on knowledge/sports/athletes/jason_kelce/qna.yaml
> +    - jason_kelce.md
```suggestion
document:
  repo: https://github.com/juliadenham/Summit_knowledge
  commit: 91e2f2d887a256c391ff36933f422c064524968c
  patterns:
    - jason_kelce.md
```

2024-05-31 14:59 UTC, jjasghar commented
I dare say that with your edits, @bjhargrave, you may have just created the "best" version to show as an example `qna.yaml` file for people to learn how to ask the questions.

2024-06-10 18:46 UTC, jjasghar commented
@instructlab-bot precheck

2024-08-19 21:28 UTC, jjasghar commented
Hi! :wave:
With the new update and release of 0.18.0, our [base knowledge submissions](https://github.com/instructlab/taxonomy/?tab=readme-ov-file#knowledge-yaml-examples) have drastically changed. This has given us an opportunity to significantly improve the accuracy of our fine-tuned models, which is a major win for our community!

But alas, that has caused some changes that this PR isn't able to continue forward. We greatly appreciate the work you've put into this, and wish we could accept it but the amount of work to get it to be `version: 3` is unrealistic for us to ask.
If you _do_ want to do this, please don't hesitate to take the `qna.yaml` update it, and build it out. Otherwise, we hope you come back to our community with a new submission and help build out our Open Source community-driven LLM.

If you have any questions directly, please don't hesitate to comment on the PR or email me at [awesomeATinstructlab.ai](http://awesomeatinstructlab.ai/) (yes, really), and I'll do my best to answer your questions.

2024-08-19 21:28 UTC, closed without merging