Removed wikilink from the knowledge example
instructlab/taxonomy pull request #1266
Opened 2024-08-08 21:20 UTC by jjasghar

- Removed wikilink code
- Added an array for the document section

/cc @juliadenham

2024-08-12 20:10 UTC, jjasghar commented
Closed per the triage meeting. This will be needed to be done at a later date.

2024-08-19 21:59 UTC, jjasghar commented
Should we redo this one now after the changes from https://github.com/juliadenham/Summit_knowledge/pull/1 ? @juliadenham

2024-08-20 14:40 UTC, bjhargrave requested changes

2024-08-20 18:52 UTC, bjhargrave approved these changes

2024-08-20 18:54 UTC, merged