Knowledge: Fifa's laws of the game
instructlab/taxonomy pull request #1350
Opened 2024-11-22 19:53 UTC by gtyellow

These are the international rules for soccer.  They are called the laws of the game.

2024-12-01 17:13 UTC, jjasghar commented
Please fix the DCO, and I'm surprised this isn't already in the model(s). We'll have to run this against the backend to see if there is a value add here.

2024-12-01 17:45 UTC, gtyellow commented
I'm really not sure. I was trying to learn instruct lab so I just came up with something somewhat random.  The laws of the game for soccer which are really just the rules of the game, are all over the Internet so I'm guessing it's in the model already?

If I can make a suggestion, you may want to add some examples of things that you want to add that might improve the model. I also don't know what the dco is.

Jeff A Duncan
919-757-6245
________________________________
From: JJ Asghar ***@***.***>
Sent: Sunday, December 1, 2024 12:13:39 PM
To: instructlab/taxonomy ***@***.***>
Cc: gtyellow ***@***.***>; Author ***@***.***>
Subject: Re: [instructlab/taxonomy] Knowledge: Fifa's laws of the game (PR #1350)


Please fix the DCO, and I'm surprised this isn't already in the model(s). We'll have to run this against the backend to see if there is a value add here.

—
Reply to this email directly, view it on GitHub<https://github.com/instructlab/taxonomy/pull/1350#issuecomment-2510060339>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXYTMK2RFMJ25AWS2DPVASD2DM7UHAVCNFSM6AAAAABSKBY3UOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMJQGA3DAMZTHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-12-02 21:15 UTC, jjasghar commented
@instructlab-bot precheck

2024-12-02 21:20 UTC, jjasghar requested changes
Also please fix the DCO.

2024-12-02 21:20 UTC, jjasghar commented on knowledge/miscellaneous_unknown/qna.yaml
> +  - context: This is the rules of the shape and dimensions of a field
The `context` should be a specific section from the referenced document that you declare at the bottom of this `yaml`.

2024-12-02 21:20 UTC, jjasghar commented on knowledge/miscellaneous_unknown/qna.yaml
> +document_outline: >-
The `document_outline` should be a "one liner" descriptive overview of the submission. This should be concise yet descriptive enough for an LLM to build context.

2024-12-02 21:20 UTC, jjasghar commented on knowledge/miscellaneous_unknown/qna.yaml
> +  - context: This is the rules of the shape and dimensions of a field
RE: https://github.com/instructlab/taxonomy/blob/main/README.md#knowledge-yaml-examples

2024-12-19 22:32 UTC, davidmalcolm commented on knowledge/miscellaneous_unknown/qna.yaml
> +          If a player who isn't the goalies touches the ball from the tips of
Suspected typo: "goalies" -> "goalie"

2024-12-19 22:35 UTC, davidmalcolm commented
An interesting soccer-related question might be "Please explain the offside rule to me in simple terms" :)

2025-02-06 02:02 UTC, closed without merging