Add pattern checks for linting
instructlab/taxonomy pull request #1374
Opened 2024-12-19 22:06 UTC by nimbinatus

Fixes #1369 

Adds in three pattern checks to address issues discovered during triage. Warns as these will not break code, but rather are specific to legal requirements (best actual documentation I can find is https://github.com/instructlab/taxonomy/blob/main/README.md?plain=1#L284-L287, but this information was discussed in a triage meeting with @jjasghar and @juliadenham).

Also, hides `uv`-specific files from git.

2025-01-06 21:28 UTC, nimbinatus commented
(Also, does squash and merge not work here in this repo, so I need to squash and force push to clean up history before merging on my own?)

2025-01-06 23:10 UTC, bjhargrave requested changes

2025-01-06 23:10 UTC, bjhargrave commented on scripts/check-yaml.py
> +                        if not re.match('.*.md', element):
I thought pdf support was added? Anyway the regex here would be 

`re.search("\.md$", element)`

But what about the pattern `folder_of_md_files/*` which is a legitimate value which should not be rejected.

If you want to do more checking here, I don't think you can do it by pattern matching the yaml contents. You would need to clone the repo, find all files in the repo which match the patterns, and then check that all those files match the desired file types.

2025-01-06 23:10 UTC, bjhargrave commented on scripts/check-yaml.py
> +                            "GitHub-based repository.",
No it doesn't have to be GitHub. Any valid git repo could be used. We just expect that any such git repo can be accessed because any necessary authorization is configured.

2025-01-06 23:10 UTC, bjhargrave commented on scripts/check-yaml.py
> +                    if not re.match(
This potential check is discussed here: https://github.com/instructlab/schema/issues/30

If we do want to require SHA values, we should probably do that in the schema. But I am not convinced that is a great idea. Since we could allow non-SHA values that have special meanings.

2025-01-06 23:45 UTC, nimbinatus commented on scripts/check-yaml.py
> +            if taxonomy.warnings > 0:
Oh bugger, you're right; I'm resetting the exit code. Sorry; fixing that.

2025-01-07 21:43 UTC, nimbinatus commented on scripts/check-yaml.py
> +                        if not re.match('.*.md', element):
Yes, pdf support was added in the recent release. Oversight on my part as a newbie.

Technically, the `.*` should match directory patterns when used with `re.match()` and has in the testing I've done, but you're right on the higher level that I probably shouldn't be matching file patterns (I really should be just parsing the string instead of getting into regex at all...) and should be validating the file type from the repo.  Was there a reason the prior version at https://github.com/instructlab/taxonomy/pull/1192 was dropped, or did it just lack contributor time?

2025-01-07 21:44 UTC, nimbinatus commented on scripts/check-yaml.py
> +                            "GitHub-based repository.",
I've been getting conflicting information on this as I've onboarded onto the project, so I'm validating that with oversight first (left a note in the taxonomy triage channel on InstructLab Slack to get more info). I'll update this when I get an answer there.

2025-01-23 18:42 UTC, nimbinatus commented
I'm going to close this PR as there's some wider questions going on in the community about what the pull requests will need. No need for these warnings until we get that sorted out, and I can revisit this branch in a new PR.

2025-01-23 18:42 UTC, closed without merging