taxonomy sync with internal repo
instructlab/taxonomy pull request #561
Opened 2024-03-18 18:49 UTC by shivchander

Syncing taxonomy repo with internal backend repo

--- update on Mar 22 by @xukai92 ---

Adding more details here as there is some confusion around about where the files in the PR come from.

TLDR; This PR was to sync the existing `seed_examples` that have been created during the original LAB development (before InstructLab started), and yes currently the `taxonomy` repo in `instruct-lab` is the only process to contribute YAML files (i.e. there is no other hidden/internal process).

Also want to share some more contexts here to make what have been going on more transparent.

During the initial research/development phase of LAB, the team tested a lot of ideas of synthetic data generation.
For that purpose, the `seed_examples` were mostly in different scripts and notebooks (owned by different people) and the examples were not in the clean&neat structure as YAML files as the current `taxonomy` repo has.
When the InstructLab effort began, we pushed a small subset that we quickly cleaned up to get started.
Since then, the team (mostly hard work done by Shiv and Abhishek) has been working on cleaning up the internal data into YAML files (extracting from various notebooks/scripts, putting them at the right paths, consolidating the formats as agreed in the `taxonomy` repo, etc., etc.).
We've been working on this for a while but it is a time-consuming process: it was only finished a few days before that this PR was created and merged.
But hopefully by having the data during the original development in the repo now, there are more reference examples and more structure to help people make further contributions :slightly_smiling_face:

2024-03-18 19:04 UTC, xukai92 requested changes

2024-03-18 20:28 UTC, bmr-cymru reviewed
There seems to be some possible personally identifiable information in this commit and it's missing the `attribtion` values added in #492.

2024-03-18 20:35 UTC, xukai92 approved these changes

2024-03-19 17:37 UTC, xukai92 approved these changes

2024-03-19 17:37 UTC, merged