Added Softball knowledge QandA
instructlab/taxonomy pull request #659
Opened 2024-04-04 20:57 UTC by jjasghar

Added a knowledge `qna.yaml` for softball.

2024-04-04 21:21 UTC, mingxzhao requested changes

2024-04-05 14:07 UTC, mingxzhao approved these changes
LGTM, I'll mark it as approved

2024-04-19 19:31 UTC, closed without merging

2024-04-22 00:53 UTC, n1hility commented
Thank you for your contribution to InstructLab! Unfortunately, once a Github repo is made public, all open PRs are automatically closed since they link against a private repo. We have detected that your PR might have been one of the ones affected by this change. If you are still interested in contributing your improvement, please fill out the following short form by no later than May 3rd, and we will get back to you with the additional steps necessary once we have had time to assess the PRs of those still interested:

https://forms.gle/V7SrPPMZDo6iGDYu8

2024-06-05 19:29 UTC, alinaryan commented
Thank you for your submission. Here are your results: 
Your PR didn't change the model performance 
The model's new score is: 0.5108695652173914 
 The old score was: 0.5108695652173914 
||||||||||||||||||||||||||||||||||||||||||||||||||| 51.08695652173913%