skill: Add reasoning skill about siblings
instructlab/taxonomy pull request #736
Opened 2024-04-21 23:32 UTC by russellb

This skill was inspired by one of the tests included in mt-bench. It included some questions that the model answered incorrectly. When given the same question manually, I got the following incorrect answer:

> Q: David has three sisters. Each of them has one brother. How many
>    brothers does David have?
> A: David has three sisters, and each of them has one brother, so it
>    must be the same brother in all cases. Therefore, David has 1 brother.

2024-04-21 23:33 UTC, russellb commented
Originally posted as #365

2024-04-21 23:33 UTC, russellb commented
@instructlab-bot precheck

2024-04-21 23:33 UTC, russellb commented
@instructlab-bot generate

2024-04-23 04:29 UTC, mingxzhao requested changes
Based on SDG, seems model will have a bit of trouble coming up with good synthetic data. One problem that I can see beyond logical flaws is the gendering of the names. We assume David is male but model may not make same assumption, thus the question of # of brothers is more ambiguous.

2024-04-23 04:49 UTC, russellb commented
> Based on SDG, seems model will have a bit of trouble coming up with good synthetic data. One problem that I can see beyond logical flaws is the gendering of the names. We assume David is male but model may not make same assumption, thus the question of # of brothers is more ambiguous.

good feedback, thanks. I'll look at trying to improve this at some point, or I'm happy to take suggested improvements from anyone interested.

For reference, this was based on something the model didn't do well with mt-bench.

https://github.com/lm-sys/FastChat/blob/f22f2194c9152a25d2987e5118206e3bbb9efd5e/fastchat/llm_judge/data/mt_bench/question.jsonl#L24

2024-04-23 04:59 UTC, mingxzhao commented
Ah I see, then I may just have to go argue with the mt-bench mods. Maybe try prefacing the question and confirming David is a male. I have doubts if this will allow the model to solve but it would at least tell us if the assumption of David's gender was the issue with the model reasoning.

2024-04-23 20:52 UTC, RobotSail commented
To fix this PR, please run `git rebase -i upstream/main` and set the operations to:
```
drop 1966cef feat(synthetic data): Add script to generate synthetic data readme (#650)
drop cc381ec Updating org name from instruct-lab to instructlab (#711)
pick ed04050 skill: Add reasoning skill about siblings
```

2024-06-07 17:19 UTC, jjasghar commented
@instructlab-bot precheck

2024-08-28 18:45 UTC, bjhargrave commented
I relocated the folder to the new taxonomy organization. I also updated the seed examples to be more specific about whether the subject is a brother or sister instead of making assumption from the name.

2024-08-28 18:46 UTC, bjhargrave approved these changes

2024-09-23 18:47 UTC, mcorbin-ibm commented
@bjhargrave 
> I relocated the folder to the new taxonomy organization (compositional_skills/philosophy/logic/induction/siblings/)

I think I would change "induction" to "inductive_reasoning" because induction has too many other connotations and inductive_reasoning makes it more apparent.

2025-01-06 21:27 UTC, jjasghar commented
Please reopen this with the new model 3.0 as the tested against.

2025-01-06 21:27 UTC, closed without merging