interstate gaps
instructlab/taxonomy pull request #861
Opened 2024-05-07 17:48 UTC by earvonen

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-07 18:41 UTC, mingxzhao commented
@instructlab-bot precheck

2024-05-07 18:48 UTC, mingxzhao requested changes

2024-05-07 18:48 UTC, mingxzhao commented on knowledge/highways/gaps_in_interstate/qna.yaml
> +  question: What are true gaps?
Hey there, thank you so much for your submission! To help the process a bit, it is important, particularly with knowledge, to be as specific as possible. In this case we can see in the precheck that the model thinks the true gap refers to a math principal. Maybe try "what is a true gap in the context of Interstate Highways"

2024-05-31 19:22 UTC, jjasghar commented
Closing per #1146

2024-05-31 19:22 UTC, closed without merging