Add files via upload
instructlab/taxonomy pull request #907
Opened 2024-05-08 18:01 UTC by antmanlinux

https://github.com/instructlab/taxonomy/issues/788

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-08 18:17 UTC, bjhargrave requested changes
Please update to address the review comments.

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +created_by:
This value must be your github id.

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +Dolly the sheep was a female Finn-Dorset sheep and the first mammal that was cloned from an adult somatic cell
This line needs to be indented to be proper yaml.

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +Dolly the sheep was a female Finn-Dorset sheep and the first mammal that was cloned from an adult somatic cell
```suggestion
- answer: |
    Dolly the sheep was a female Finn-Dorset sheep and the first mammal that was cloned from an adult somatic cell
```

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +Her cloning proved that a cloned organism could be produced from a mature cell from a specific body part.
```suggestion
- answer: |
    Her cloning proved that a cloned organism could be produced from a mature cell from a specific body part.
```

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +Contrary to popular belief, she was not the first animal to be cloned.
```suggestion
- answer: |
    Contrary to popular belief, she was not the first animal to be cloned.
```

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> + based near Edinburgh.
```suggestion
- answer: |
    Dolly was cloned by Keith Campbell, Ian Wilmut and colleagues at the Roslin Institute, 
    part of the University of Edinburgh, Scotland, and the biotechnology company PPL Therapeutics,
    based near Edinburgh. 
```

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +On 14 February 2003
```suggestion
- answer: |
    On 14 February 2003
```

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +Dolly was euthanised because she had a progressive lung disease and severe arthritis.
```suggestion
- answer: |
    Dolly was euthanised because she had a progressive lung disease and severe arthritis.
```

2024-05-08 18:17 UTC, bjhargrave commented on knowledge/animals/cloning/dolly_the_sheep/qna.yaml
> +task_description: ' '
Please provide a task description as this is used by the synthetic data generation process.

2024-08-19 21:49 UTC, jjasghar commented
Hi! :wave:
With the new update and release of 0.18.0, our [base knowledge submissions](https://github.com/instructlab/taxonomy/?tab=readme-ov-file#knowledge-yaml-examples) have drastically changed. This has given us an opportunity to significantly improve the accuracy of our fine-tuned models, which is a major win for our community!
But alas, that has caused some changes that this PR isn't able to continue forward. We greatly appreciate the work you've put into this, and wish we could accept it but the amount of work to get it to be `version: 3` is unrealistic for us to ask.
If you _do_ want to do this, please don't hesitate to take the `qna.yaml` update it, and build it out. Otherwise, we hope you come back to our community with a new submission and help build out our Open Source community-driven LLM.

If you have any questions directly, please don't hesitate to comment on the PR or email me at awesomeATinstructlab.ai (yes, really), and I'll do my best to answer your questions.

2024-08-19 21:49 UTC, closed without merging