Add files via upload
instructlab/taxonomy pull request #932
Opened 2024-05-08 20:04 UTC by everythingeverywhere

https://github.com/instructlab/taxonomy

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-08 20:05 UTC, everythingeverywhere commented
https://github.com/instructlab/taxonomy

2024-05-09 17:37 UTC, jjasghar commented
Please fix this so it's in the correct taxonomy leaf node (directory).

2024-05-13 23:02 UTC, jjasghar requested changes
Please resolve these issues then we can run the linter.

2024-05-13 23:02 UTC, jjasghar commented on attribution.txt
Please put this file in the correct directory.

2024-05-13 23:02 UTC, jjasghar commented on qna.yaml
Please put this file in the correct directory.

2024-05-13 23:02 UTC, jjasghar commented on qna.yaml
> +- answer: | a type of radioisotope thermoelectric generator (RTG) developed for NASA space missions[1] such as the Mars Science Laboratory (MSL), under the jurisdiction of the United States Departmen
Thank you for your submission; taking a look at your `qna.yaml`, we noticed that you have some issues with the multiline `yaml` syntax.

Can you take a look at: https://yaml-multiline.info/ and fix up the file? Thanks!

2024-05-30 20:48 UTC, jjasghar commented
Closing due to combined PR here:  #1142

2024-05-30 20:48 UTC, closed without merging