Add files via upload
instructlab/taxonomy pull request #940
Opened 2024-05-08 20:44 UTC by pcasal

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-08 20:45 UTC, pcasal commented
This is a contribution to the Phoenix Constellation knowledge - https://github.com/instructlab/taxonomy/issues/830

2024-05-13 22:30 UTC, jjasghar requested changes
Please fix these issues then we can run the linter.

2024-05-13 22:30 UTC, jjasghar commented on knowledge/astronomy/constellations/Phoenix/qna.yaml
> +created_by: Pablo Casal pcasal@gmail.com
Please put your GitHub Username here.

2024-05-13 22:30 UTC, jjasghar commented on knowledge/astronomy/constellations/Phoenix/qna.yaml
> +- answer: The constellation does not lie on the galactic plane of the Milky Way, and there are no prominent star clusters. Lying within the bounds of the constellation is the gigantic Phoenix cluster
Thank you for your submission; taking a look at your `qna.yaml`, we noticed that you have some issues with the multiline `yaml` syntax.

Can you take a look at: https://yaml-multiline.info/ and fix up the file? Thanks!

2024-06-04 17:38 UTC, jjasghar commented
Closing per the combined PR here: https://github.com/instructlab/taxonomy/pull/1159

2024-06-04 17:38 UTC, closed without merging