Add files via upload
instructlab/taxonomy pull request #954
Opened 2024-05-08 21:35 UTC by philippfe

https://github.com/instructlab/taxonomy/issues/835

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-16 01:47 UTC, jjasghar requested changes
Please fix the file name issue, then we can run the linter.

2024-05-16 01:47 UTC, jjasghar commented on knowledge/science/botany/jasminum/qna.txt
Please change this file name to `qna.yaml`

2024-05-16 07:58 UTC, philippfe commented on knowledge/science/botany/jasminum/qna.txt
very sorry - I renamed the file

2024-05-17 20:12 UTC, jjasghar requested changes
Please fix the linting issue.

2024-05-21 09:47 UTC, philippfe commented
Hi, I fixed the issues - the only I thing the linter mentioned which I couldn't identify is the error in line 6, stating a missing ":". In my opinion everything looks fine and should work, similar to the other questions.
Please let me know, if I'm missing something.
Thanks for your help and patience!

2024-05-21 21:43 UTC, jjasghar requested changes
Please resolve the linting issues.

2024-05-22 09:26 UTC, philippfe commented
Linting issues should be fixed now.
Kind regards,
Philipp

2024-05-22 21:39 UTC, jjasghar requested changes
Please check here for the linting issues, you have a few still hanging around :)

2024-05-24 10:10 UTC, philippfe commented
Hm, yes it seems, I have added new issues, sorry - will fix it asap

2024-05-28 19:17 UTC, jjasghar requested changes
Please fix the linting issues listed here: https://github.com/instructlab/taxonomy/pull/954/files

2024-05-29 22:54 UTC, jjasghar commented
Closed due to the combined PR here: https://github.com/instructlab/taxonomy/pull/1140

2024-05-29 22:54 UTC, closed without merging