Add files via upload
instructlab/taxonomy pull request #960
Opened 2024-05-08 21:52 UTC by eadamsintel

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

I am doing the instruct lab at the Red Hat Summit. I hope that my contribution helps!

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-08 21:53 UTC, eadamsintel commented
https://github.com/instructlab/taxonomy/issues/811

2024-05-13 22:27 UTC, jjasghar requested changes
Please make these changes then we can run the linter.

2024-05-13 22:27 UTC, jjasghar commented on knowledge/laws/traffic_laws_us/qna.txt
Please change the name to `qna.yaml`

2024-05-13 22:27 UTC, jjasghar commented on knowledge/laws/traffic_laws_us/qna.txt
> +created_by:
Please add your GitHub username here.

2024-05-13 22:27 UTC, jjasghar commented on knowledge/laws/traffic_laws_us/qna.txt
> +  Speed limits are set by each state or territory, as well as counties or municipalities, on the roads within their jurisdiction. The maximum speed limit on rural two-lane roads ranges from 50 mph (8
Thank you for your submission; taking a look at your `qna.yaml`, we noticed that you have some issues with the multiline `yaml` syntax.

Can you take a look at: https://yaml-multiline.info/ and fix up the file? Thanks!

2024-05-22 23:52 UTC, eadamsintel commented
I hopefully fixed this. I don't normally make edits directly from the GitHub UI so hopefully this went through OK.

2024-05-23 17:33 UTC, jjasghar requested changes
Please check the files on this PR for the linting issues you're missing.

2024-06-03 18:22 UTC, jjasghar commented
Closing per combined PR here: https://github.com/instructlab/taxonomy/pull/1151

2024-06-03 18:22 UTC, closed without merging