Add files via upload
instructlab/taxonomy pull request #967
Opened 2024-05-08 22:29 UTC by dacuna85

If your PR is related to a contribution to the taxonomy, please, fill
out the following questionnaire. If not, replace this whole text and the
following questionnaire with whatever information is applicable to your PR.

**Describe the contribution to the taxonomy**

- ...
- ...
- ...

**Input given at the prompt**

```
   ...
```

**Response from the original model**

```
  ...
```

**Response from the fine-tuned model**

```
  ...
```

**Contribution checklist**

- [ ] The contribution was tested with `ilab generate`
- [ ] No errors or warnings were produced by `ilab generate`
- [ ] All [commits are signed off](https://github.com/instructlab/taxonomy/blob/main/CONTRIBUTING.md#legal) (DCO)
- [ ] The `qna.yaml` file contains at least 5 `seed_examples`
- [ ] The `qna.yaml` file was [linted](https://yamllint.com) and [prettified](https://onlineyamltools.com/prettify-yaml) ([yaml-validator](https://jsonformatter.org/yaml-validator) can do both)
- [ ] An `attribution.txt` file in the same folder as the `qna.yaml` file
- [ ] Content does not include PII or otherwise sensitive or confidential information
- [ ] Content does not include anything documented in the project's [Avoid these Topics](https://github.com/instructlab/taxonomy/blob/main/docs/SKILLS_GUIDE.md#avoid-these-topics) guidelines

2024-05-08 22:30 UTC, dacuna85 commented
https://github.com/instructlab/taxonomy/issues/832

2024-05-13 22:26 UTC, jjasghar requested changes
Please make these fixes then we can run the linter.

2024-05-13 22:26 UTC, jjasghar commented on knowledge/music/events/cochella_2023/qna.yaml
> +created_by:
Please add your GitHub Username here.

2024-05-13 22:26 UTC, jjasghar commented on knowledge/music/events/cochella_2023/qna.yaml
> +- answer: Ocean's Coachella performance was harshly criticized from audience members, critics, and fans.[5] The Festive Owl, speaking to several sources, later stated that a group of people surroundi
Thank you for your submission; taking a look at your `qna.yaml`, we noticed that you have some issues with the multiline `yaml` syntax.

Can you take a look at: https://yaml-multiline.info/ and fix up the file? Thanks!

2024-05-29 18:11 UTC, closed without merging